# Generated by Django 4.1.3 on 2022-11-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerowaste", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oreview",
            name="source",
            field=models.CharField(default="OWASTE", max_length=10),
        ),
    ]
